apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5ghi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5ghi
    app.kubernetes.io/part-of: ci10t-776-0034-app
  name: devfile-sample-5ghi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-5ghi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-5ghi
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0034-tenant/ci10t-776-0034-app/devfile-sample-5ghi@sha256:e8719f1daaeba1dc0e29bc34ef08a2182050b9e3ae4550e8cbda10aea4430bbd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
